# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'readingorderitem.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ReadingOrderItem(object):
    def setupUi(self, ReadingOrderItem):
        ReadingOrderItem.setObjectName("ReadingOrderItem")
        ReadingOrderItem.resize(470, 130)
        ReadingOrderItem.setMinimumSize(QtCore.QSize(470, 38))
        self.label_title = QtWidgets.QLabel(ReadingOrderItem)
        self.label_title.setGeometry(QtCore.QRect(10, 10, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(14)
        self.label_title.setFont(font)
        self.label_title.setObjectName("label_title")
        self.label_file = QtWidgets.QLabel(ReadingOrderItem)
        self.label_file.setGeometry(QtCore.QRect(10, 40, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(14)
        self.label_file.setFont(font)
        self.label_file.setObjectName("label_file")
        self.lineEdit_title = QtWidgets.QLineEdit(ReadingOrderItem)
        self.lineEdit_title.setGeometry(QtCore.QRect(90, 10, 311, 20))
        self.lineEdit_title.setObjectName("lineEdit_title")
        self.lineEdit_file = QtWidgets.QLineEdit(ReadingOrderItem)
        self.lineEdit_file.setGeometry(QtCore.QRect(90, 40, 261, 20))
        self.lineEdit_file.setObjectName("lineEdit_file")
        self.pushButton_Browse = QtWidgets.QPushButton(ReadingOrderItem)
        self.pushButton_Browse.setGeometry(QtCore.QRect(360, 40, 62, 22))
        self.pushButton_Browse.setMinimumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(14)
        self.pushButton_Browse.setFont(font)
        self.pushButton_Browse.setObjectName("pushButton_Browse")
        self.lineEdit_URL = QtWidgets.QLineEdit(ReadingOrderItem)
        self.lineEdit_URL.setGeometry(QtCore.QRect(90, 70, 331, 20))
        self.lineEdit_URL.setObjectName("lineEdit_URL")
        self.label_duration = QtWidgets.QLabel(ReadingOrderItem)
        self.label_duration.setGeometry(QtCore.QRect(10, 100, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(14)
        self.label_duration.setFont(font)
        self.label_duration.setObjectName("label_duration")
        self.lineEdit_duration = QtWidgets.QLineEdit(ReadingOrderItem)
        self.lineEdit_duration.setGeometry(QtCore.QRect(110, 100, 291, 20))
        self.lineEdit_duration.setReadOnly(True)
        self.lineEdit_duration.setObjectName("lineEdit_duration")
        self.label_URL = QtWidgets.QLabel(ReadingOrderItem)
        self.label_URL.setGeometry(QtCore.QRect(10, 70, 31, 16))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(14)
        self.label_URL.setFont(font)
        self.label_URL.setObjectName("label_URL")
        self.pushButton_UpDown = QtWidgets.QPushButton(ReadingOrderItem)
        self.pushButton_UpDown.setGeometry(QtCore.QRect(430, 0, 31, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_UpDown.sizePolicy().hasHeightForWidth())
        self.pushButton_UpDown.setSizePolicy(sizePolicy)
        self.pushButton_UpDown.setMinimumSize(QtCore.QSize(24, 24))
        self.pushButton_UpDown.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Up-20.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_UpDown.setIcon(icon)
        self.pushButton_UpDown.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_UpDown.setObjectName("pushButton_UpDown")
        self.radioButton_file = QtWidgets.QRadioButton(ReadingOrderItem)
        self.radioButton_file.setGeometry(QtCore.QRect(70, 40, 21, 21))
        self.radioButton_file.setMinimumSize(QtCore.QSize(21, 21))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(14)
        self.radioButton_file.setFont(font)
        self.radioButton_file.setText("")
        self.radioButton_file.setChecked(True)
        self.radioButton_file.setObjectName("radioButton_file")
        self.radioButton_URL = QtWidgets.QRadioButton(ReadingOrderItem)
        self.radioButton_URL.setGeometry(QtCore.QRect(70, 70, 21, 21))
        self.radioButton_URL.setMinimumSize(QtCore.QSize(21, 21))
        self.radioButton_URL.setText("")
        self.radioButton_URL.setChecked(False)
        self.radioButton_URL.setObjectName("radioButton_URL")

        self.retranslateUi(ReadingOrderItem)
        QtCore.QMetaObject.connectSlotsByName(ReadingOrderItem)

    def retranslateUi(self, ReadingOrderItem):
        _translate = QtCore.QCoreApplication.translate
        ReadingOrderItem.setWindowTitle(_translate("ReadingOrderItem", "Form"))
        self.label_title.setText(_translate("ReadingOrderItem", "title:"))
        self.label_file.setText(_translate("ReadingOrderItem", "file:"))
        self.pushButton_Browse.setText(_translate("ReadingOrderItem", "Browse"))
        self.label_duration.setText(_translate("ReadingOrderItem", "duration:"))
        self.label_URL.setText(_translate("ReadingOrderItem", "URL:"))
